function adminEscape(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function adminAge(date){if(!date)return '—';const b=new Date(date+'T12:00:00'),n=new Date();let a=n.getFullYear()-b.getFullYear();if(n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))a--;return a}
function embedUrl(url){try{const u=new URL(url);if(u.hostname==='youtu.be')return `https://www.youtube.com/embed/${u.pathname.slice(1)}`;if(u.hostname.includes('youtube.com'))return `https://www.youtube.com/embed/${u.searchParams.get('v')}`;if(u.hostname.includes('vimeo.com'))return `https://player.vimeo.com/video/${u.pathname.split('/').filter(Boolean).pop()}`;}catch{}return ''}
function adminVideo(url,label){const e=embedUrl(url);return e?`<div class="admin-video"><strong>${label}</strong><iframe src="${adminEscape(e)}" title="${label}" loading="lazy" allowfullscreen></iframe></div>`:''}
async function initAdminPanel(){
  const root=document.getElementById('adminPanel');if(!root)return;
  if(!RDA?.configured){root.innerHTML='<div class="notice">Primero configurá Supabase para activar Administración.</div>';return}
  const session=await RDA.session();if(!session){location.href='login.html';return}
  if(!(await RDA.isAdmin())){root.innerHTML='<div class="rejected-panel"><strong>ACCESO RESTRINGIDO</strong><p>Esta sección existe únicamente para administradores de Córdoba Casting.</p></div>';return}
  await renderAdminPanel('pending');
}
async function renderAdminPanel(tab='pending'){
  const root=document.getElementById('adminPanel');
  const [all,reports]=await Promise.all([RDA.allProfiles(),RDA.reports().catch(()=>[])]);
  const pending=all.filter(p=>p.status==='pending'),rejected=all.filter(p=>p.status==='rejected'),published=all.filter(p=>p.status==='approved');
  const list=tab==='pending'?pending:tab==='approved'?published:tab==='rejected'?rejected:[];
  root.innerHTML=`<div class="admin-head"><div><div class="eyebrow">Córdoba Casting</div><h1>Administración</h1><p class="muted">Revisá altas nuevas y administrá perfiles existentes.</p></div><a class="btn btn-secondary" href="index.html">Ver sitio</a></div>
  <div class="admin-tabs"><button data-tab="pending" class="${tab==='pending'?'active':''}">Pendientes <span>${pending.length}</span></button><button data-tab="approved" class="${tab==='approved'?'active':''}">Publicados <span>${published.length}</span></button><button data-tab="rejected" class="${tab==='rejected'?'active':''}">Rechazados <span>${rejected.length}</span></button><button data-tab="reports" class="${tab==='reports'?'active':''}">Reportes <span>${reports.length}</span></button></div>
  <div class="admin-list">${tab==='reports'?renderReports(reports,all):(list.length?list.map(p=>adminCard(p,tab)).join(''):'<div class="admin-empty">No hay perfiles en esta sección.</div>')}</div>`;
  root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>renderAdminPanel(b.dataset.tab));
  root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleAdminAction(b));
  root.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=async()=>{await RDA.resolveReport(b.dataset.resolve);await renderAdminPanel('reports')});
}
function renderReports(reports,all){if(!reports.length)return '<div class="admin-empty">No hay reportes pendientes.</div>';return reports.map(r=>{const p=all.find(x=>x.id===r.actor_id);return `<article class="report-card"><div><strong>${adminEscape(p?.display_name||'Perfil')}</strong><p>${adminEscape(r.reason)}</p><small>${new Date(r.created_at).toLocaleString('es-AR')}</small></div><div class="admin-profile-actions"><a class="btn btn-secondary" href="actor.html?id=${encodeURIComponent(p?.slug||r.actor_id)}" target="_blank">Ver perfil</a><button class="btn btn-secondary" data-resolve="${r.id}">Marcar resuelto</button></div></article>`}).join('')}
function adminCard(p,tab){
  const skills=(p.skills||[]).map(x=>`<span class="tag">${adminEscape(x)}</span>`).join('');
  const photos=[p.photo_url,p.photo_url_2,p.photo_url_3].filter(Boolean).map(u=>`<img src="${adminEscape(u)}" alt="Foto">`).join('');
  return `<article class="admin-profile-card"><div class="admin-profile-photo">${p.photo_url?`<img src="${adminEscape(p.photo_url)}" alt="${adminEscape(p.display_name)}">`:'<div class="no-photo">Sin foto</div>'}</div><div class="admin-profile-main"><div class="admin-profile-title"><div><h3>${adminEscape(p.display_name||'Perfil sin nombre')}</h3><p>${adminAge(p.birth_date)} años · ${adminEscape(p.city||'Sin localidad')}</p></div><span class="profile-state state-${p.status}">${p.status}</span></div><div class="admin-flags"><span>${p.is_available?'● Disponible ahora':'○ No disponible'}</span>${p.accepts_student_work?'<span>🎓 Acepta estudiantiles</span>':''}${p.is_featured?'<span>★ Destacado</span>':''}${p.is_hidden?'<span>◉ Oculto</span>':''}</div><p class="admin-bio">${adminEscape(p.bio||'')}</p><div class="tags">${skills}</div><div class="admin-photo-strip">${photos}</div><div class="admin-media">${adminVideo(p.presentation_url,'Video de presentación')}${adminVideo(p.reel_url,'Reel')}${adminVideo(p.monologue_url,'Monólogo / escena')}</div>${p.status==='rejected'&&p.rejection_reason?`<div class="admin-reason"><strong>Motivo:</strong> ${adminEscape(p.rejection_reason)}</div>`:''}</div><div class="admin-profile-actions">${tab==='pending'?`<button class="btn btn-primary" data-action="approve" data-id="${p.id}">Aprobar</button><button class="btn btn-secondary" data-action="reject" data-id="${p.id}">Rechazar</button>`:''}${tab==='approved'?`<a class="btn btn-secondary" href="actor.html?id=${encodeURIComponent(p.slug||p.id)}" target="_blank">Ver público</a><button class="btn btn-secondary" data-action="${p.is_featured?'unfeature':'feature'}" data-id="${p.id}">${p.is_featured?'Quitar destacado':'★ Destacar'}</button><button class="btn btn-secondary" data-action="${p.is_hidden?'show':'hide'}" data-id="${p.id}">${p.is_hidden?'Volver a mostrar':'Ocultar'}</button><button class="btn btn-danger" data-action="delete" data-id="${p.id}" data-name="${adminEscape(p.display_name||'este actor')}">Eliminar</button>`:''}${tab==='rejected'?'<span class="tiny muted">Volverá a Pendientes cuando el actor corrija y guarde.</span>':''}</div></article>`
}
async function handleAdminAction(btn){const {action,id}=btn.dataset;let reason='';if(action==='reject'){reason=prompt('Motivo del rechazo. El actor lo verá al iniciar sesión:','');if(!reason?.trim())return alert('Para rechazar un perfil tenés que indicar el motivo.');}if(action==='delete'){if(!confirm(`¿Eliminar definitivamente la cuenta de ${btn.dataset.name}? Esta acción no se puede deshacer.`))return;btn.disabled=true;try{await RDA.deleteActor(id);await renderAdminPanel('approved')}catch(e){alert(e.message)}return}btn.disabled=true;try{await RDA.moderate(id,action,reason.trim());await renderAdminPanel(document.querySelector('.admin-tabs .active')?.dataset.tab||'pending')}catch(err){alert(err.message||'No se pudo realizar la acción.');btn.disabled=false}}
document.addEventListener('DOMContentLoaded',initAdminPanel);
