function ageFromBirth(dateStr){const b=new Date(dateStr+'T12:00:00');const n=new Date();let a=n.getFullYear()-b.getFullYear();const m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a}
function daysSince(dateStr){return Math.max(0,Math.floor((Date.now()-new Date(dateStr+'T12:00:00'))/86400000))}
function activeActors(){const hidden=JSON.parse(localStorage.getItem('rda_hidden')||'[]');return window.ACTORS.filter(a=>!hidden.includes(a.id))}
function featuredActors(){const overrides=JSON.parse(localStorage.getItem('rda_featured')||'{}');return activeActors().filter(a=>overrides[a.id]!==undefined?overrides[a.id]:a.featured)}
function card(a,featured=false){const skills=a.skills.slice(0,3).map(s=>`<span class="tag">${s}</span>`).join('');return `<a class="actor-card" href="actor.html?id=${a.id}">${featured?'<div class="featured-star">★</div>':''}<img class="actor-photo" src="${a.photo}" alt="${a.name}" loading="lazy"><div class="actor-body"><div class="actor-name">${a.name}</div><div class="actor-meta">${ageFromBirth(a.birth)} años · ${a.city}</div>${a.available?'<div class="status"><span class="dot"></span>Disponible ahora</div>':'<div class="actor-meta" style="margin-top:8px">No disponible</div>'}<div class="tags">${skills}</div></div></a>`}
function initNav(){const btn=document.querySelector('.menu-toggle'),links=document.querySelector('.navlinks');if(btn&&links)btn.addEventListener('click',()=>links.classList.toggle('open'))}
function renderHome(){const featured=document.querySelector('#featuredGrid'),all=document.querySelector('#actorGrid');if(!featured||!all)return;featured.innerHTML=featuredActors().slice(0,6).map(a=>card(a,true)).join('');all.innerHTML=activeActors().map(a=>card(a,false)).join('');const form=document.querySelector('#filters');form?.addEventListener('input',applyFilters);form?.addEventListener('submit',e=>{e.preventDefault();applyFilters()})}
function applyFilters(){const q=(document.querySelector('#q')?.value||'').toLowerCase().trim();const av=document.querySelector('#available')?.value||'';const st=document.querySelector('#student')?.value||'';const age=document.querySelector('#age')?.value||'';let list=activeActors().filter(a=>{const A=ageFromBirth(a.birth);const text=[a.name,a.city,...a.skills].join(' ').toLowerCase();if(q&&!text.includes(q))return false;if(av==='yes'&&!a.available)return false;if(av==='no'&&a.available)return false;if(st==='yes'&&!a.student)return false;if(st==='no'&&a.student)return false;if(age){const [min,max]=age.split('-').map(Number);if(!(A>=min&&A<=max))return false}return true});document.querySelector('#actorGrid').innerHTML=list.map(a=>card(a,false)).join('')||'<p class="muted">No encontramos perfiles con esos filtros.</p>'}
function renderActor(){const root=document.querySelector('#actorRoot');if(!root)return;const id=new URLSearchParams(location.search).get('id')||'julieta-gomez';const a=activeActors().find(x=>x.id===id)||window.ACTORS[0];document.title=`${a.name} — Red de Actores`;const thumbs=(a.photos||[a.photo]).slice(0,3).map((p,i)=>`<img src="${p}" alt="Foto ${i+1} de ${a.name}" data-photo="${p}">`).join('');root.innerHTML=`<a class="back" href="index.html">← Volver a resultados</a><div class="profile-hero"><div><img id="mainPhoto" class="profile-photo" src="${a.photo}" alt="${a.name}"><div class="thumbs">${thumbs}</div></div><div class="profile-info">${a.available?'<span class="status-pill">● Disponible ahora</span>':''}<h1>${a.name}</h1><div class="profile-line">${ageFromBirth(a.birth)} años · ${a.city}</div><div class="profile-actions"><button class="btn btn-primary" data-contact>✉ Contactar</button><button class="btn btn-secondary" data-share>↗ Compartir perfil</button></div><div class="profile-divider"></div><div class="profile-section"><h3>Trabajos estudiantiles / no remunerados</h3><p>${a.student?'✓ Sí, acepta este tipo de proyectos':'No acepta actualmente este tipo de proyectos'}</p></div><div class="profile-divider"></div><div class="profile-section"><h3>Sobre mí</h3><p>${a.bio}</p></div><div class="profile-section"><h3>Habilidades <span class="muted">(máx. 7)</span></h3><div class="tags">${a.skills.map(s=>`<span class="tag paper-tag">${s}</span>`).join('')}</div></div></div></div><div class="profile-video-grid"><div><div class="video-label">VIDEO DE PRESENTACIÓN <small>Obligatorio</small></div>${videoBox(a.presentation,a.photo,'video-main')}</div><div class="video-side">${a.reel?`<div><div class="video-label">REEL <small>Opcional</small></div>${videoBox(a.reel,a.photo,'video-small')}</div>`:''}${a.monologue?`<div><div class="video-label">MONÓLOGO / ESCENA <small>Opcional</small></div>${videoBox(a.monologue,a.photo,'video-small')}</div>`:''}</div></div><div class="profile-bottom"><div class="muted">Última actualización: hace ${daysSince(a.updated)} días</div><button class="btn btn-primary" data-contact>✉ CONTACTAR</button></div>`;document.querySelectorAll('[data-photo]').forEach(t=>t.addEventListener('click',()=>document.querySelector('#mainPhoto').src=t.dataset.photo));document.querySelectorAll('[data-video]').forEach(v=>v.addEventListener('click',()=>openVideo(v.dataset.video)));document.querySelectorAll('[data-share]').forEach(b=>b.addEventListener('click',shareProfile));document.querySelectorAll('[data-contact]').forEach(b=>b.addEventListener('click',()=>alert('Demo V0.1: en la siguiente etapa este botón enviará el contacto privado a través de Córdoba Casting.')))}
function videoBox(url,img,cls){return `<div class="${cls}" data-video="${url}"><img src="${img}" alt="Vista previa de video"><div class="play"><span>▶</span></div></div>`}
function openVideo(url){const m=document.querySelector('#videoModal');m.querySelector('iframe').src=url;m.classList.add('open')}
function closeVideo(){const m=document.querySelector('#videoModal');if(!m)return;m.classList.remove('open');m.querySelector('iframe').src=''}
async function shareProfile(){try{if(navigator.share){await navigator.share({title:document.title,url:location.href})}else{await navigator.clipboard.writeText(location.href);alert('Enlace copiado.')}}catch(e){}}
function initModal(){document.querySelector('.modal-close')?.addEventListener('click',closeVideo);document.querySelector('#videoModal')?.addEventListener('click',e=>{if(e.target.id==='videoModal')closeVideo()})}
function initAdmin(){const grid=document.querySelector('#adminGrid');if(!grid)return;renderAdmin();function renderAdmin(){const hidden=JSON.parse(localStorage.getItem('rda_hidden')||'[]'),ft=JSON.parse(localStorage.getItem('rda_featured')||'{}');grid.innerHTML=window.ACTORS.map(a=>{const isF=ft[a.id]!==undefined?ft[a.id]:a.featured;const isH=hidden.includes(a.id);return `<div class="admin-card"><img src="${a.photo}" alt="${a.name}"><strong>${a.name}</strong><div class="tiny muted">${isH?'Oculto':'Visible'} · ${isF?'Destacado':'Normal'}</div><div class="admin-actions"><button class="btn btn-secondary" data-f="${a.id}">${isF?'Quitar destacado':'Destacar'}</button><button class="btn btn-secondary" data-h="${a.id}">${isH?'Mostrar':'Ocultar'}</button></div></div>`}).join('');grid.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{const o=JSON.parse(localStorage.getItem('rda_featured')||'{}');const a=window.ACTORS.find(x=>x.id===b.dataset.f);o[a.id]=!(o[a.id]!==undefined?o[a.id]:a.featured);localStorage.setItem('rda_featured',JSON.stringify(o));renderAdmin()});grid.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{let h=JSON.parse(localStorage.getItem('rda_hidden')||'[]');h=h.includes(b.dataset.h)?h.filter(x=>x!==b.dataset.h):[...h,b.dataset.h];localStorage.setItem('rda_hidden',JSON.stringify(h));renderAdmin()})}}
document.addEventListener('DOMContentLoaded',()=>{initNav();renderHome();renderActor();initModal();initAdmin()});
