function castEsc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function castingRoleLabel(r){const min=Number(r.min_age||0),max=Number(r.max_age||0);const age=max&&max!==min?`${min}–${max} años`:`${min} años`;return `${r.name?`${castEsc(r.name)} · `:''}${castEsc(r.gender||'')} · ${age}`}
function contactLink(c){const value=String(c.contact_value||'').trim();if(c.contact_type==='email')return `mailto:${encodeURIComponent(value)}`;if(c.contact_type==='whatsapp'){const n=value.replace(/\D/g,'');return `https://wa.me/${n}`}if(c.contact_type==='phone')return `tel:${value.replace(/[^+\d]/g,'')}`;return '#'}
function daysLeft(c){if(!c.expires_at)return '';const ms=new Date(c.expires_at)-Date.now();return Math.max(0,Math.ceil(ms/86400000))}
function castingCard(c){const roles=Array.isArray(c.roles)?c.roles:[];const left=daysLeft(c);return `<article class="casting-card casting-public-card">${c.image_url?`<a class="casting-image-wrap" href="${castEsc(c.image_url)}" target="_blank" rel="noopener"><img src="${castEsc(c.image_url)}" alt="Anuncio de casting de ${castEsc(c.project_name||c.title)}" loading="lazy"></a>`:''}<div class="casting-card-body"><div class="casting-card-top"><div><div class="eyebrow">CASTING</div><h3>${castEsc(c.project_name||c.title)}</h3></div><span class="casting-paid ${c.is_paid?'paid':'unpaid'}">${c.is_paid?'Remunerado':'No remunerado'}</span></div><div class="casting-role-pills">${roles.map(r=>`<span>${castingRoleLabel(r)}</span>`).join('')}</div>${c.requirements?`<div class="casting-detail"><strong>Requisitos excluyentes</strong><p>${castEsc(c.requirements)}</p></div>`:''}<div class="casting-card-footer"><div><small>Contacto para postularse</small><a class="casting-contact" href="${contactLink(c)}" ${c.contact_type==='whatsapp'?'target="_blank" rel="noopener"':''}>${castEsc(c.contact_value)}</a></div><span class="casting-expiry">${left===0?'Último día':left===1?'Cierra mañana':`Cierra en ${left} días`}</span></div></div></article>`}
function roleRow(index){return `<div class="casting-role-row" data-role-row><div class="field"><label>Rol / personaje <span>Opcional</span></label><input data-role-name maxlength="80" placeholder="Ej. Protagonista"></div><div class="field"><label>Género</label><select data-role-gender required><option value="Femenino">Femenino</option><option value="Masculino">Masculino</option></select></div><div class="field"><label>Edad mínima</label><input data-role-min type="number" min="1" max="100" required placeholder="25"></div><div class="field"><label>Edad máxima <span>Opcional</span></label><input data-role-max type="number" min="1" max="100" placeholder="35"></div>${index?'<button class="role-remove" type="button" data-remove-role aria-label="Eliminar rol">×</button>':''}</div>`}
function addRole(){const root=document.getElementById('castingRoles');const index=root.querySelectorAll('[data-role-row]').length;root.insertAdjacentHTML('beforeend',roleRow(index));root.querySelectorAll('[data-remove-role]').forEach(b=>b.onclick=()=>b.closest('[data-role-row]').remove())}
function collectRoles(){return [...document.querySelectorAll('[data-role-row]')].map(row=>{const min=Number(row.querySelector('[data-role-min]').value),maxRaw=row.querySelector('[data-role-max]').value;const max=maxRaw?Number(maxRaw):min;if(!min||min<1||min>100)throw new Error('Revisá la edad de los roles.');if(max<min||max>100)throw new Error('La edad máxima no puede ser menor que la mínima.');return {name:row.querySelector('[data-role-name]').value.trim()||null,gender:row.querySelector('[data-role-gender]').value,min_age:min,max_age:max}})}
function castingMessage(text,type='info'){const box=document.getElementById('castingFormMessage');box.textContent=text;box.className=`form-message span-2 ${type}`;box.hidden=false}
async function renderCastings(){const root=document.getElementById('castingList');if(!root)return;if(!RDA?.configured){root.innerHTML='<div class="notice">La sección de castings se activará al conectar Supabase.</div>';return}try{const list=await RDA.publicCastings();root.innerHTML=list.length?list.map(castingCard).join(''):'<div class="admin-empty">No hay castings abiertos por el momento.</div>'}catch(e){root.innerHTML=`<div class="notice">${castEsc(e.message)}</div>`}}
async function initCastings(){const root=document.getElementById('castingList');if(!root)return;addRole();const panel=document.getElementById('castingSubmitPanel'),show=document.getElementById('showCastingForm'),cancel=document.getElementById('cancelCastingForm');show.onclick=()=>{panel.hidden=false;show.hidden=true;panel.scrollIntoView({behavior:'smooth',block:'start'})};cancel.onclick=()=>{panel.hidden=true;show.hidden=false};document.getElementById('addCastingRole').onclick=addRole;document.getElementById('publicCastingForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.currentTarget.querySelector('[type=submit]');try{const roles=collectRoles();const image=document.getElementById('castingImage').files[0];if(!image)throw new Error('La imagen del anuncio es obligatoria.');if(image.size>5*1024*1024)throw new Error('La imagen supera el máximo de 5 MB.');btn.disabled=true;castingMessage('Subiendo la imagen y enviando el casting…');await RDA.submitPublicCasting({project_name:document.getElementById('castingProjectName').value.trim(),roles,requirements:document.getElementById('castingRequirements').value.trim()||null,is_paid:document.getElementById('castingPaid').value==='yes',duration_days:Number(document.getElementById('castingDuration').value),contact_type:document.getElementById('castingContactType').value,contact_value:document.getElementById('castingContact').value.trim()},image);castingMessage('¡Listo! El casting fue enviado a Córdoba Casting y se publicará únicamente después de ser aprobado.','success');e.currentTarget.reset();document.getElementById('castingRoles').innerHTML='';addRole()}catch(err){castingMessage(err.message||'No se pudo enviar el casting.','error')}finally{btn.disabled=false}});await renderCastings()}
document.addEventListener('DOMContentLoaded',initCastings);
