window.ACTORS = [
 {id:'julieta-gomez',name:'Julieta Gómez',gender:'actriz',birth:'2001-04-13',city:'Córdoba Capital',available:true,student:true,featured:true,updated:'2026-08-15',photo:'https://randomuser.me/api/portraits/women/44.jpg',photos:['https://randomuser.me/api/portraits/women/44.jpg','https://randomuser.me/api/portraits/women/65.jpg','https://randomuser.me/api/portraits/women/32.jpg'],skills:['Inglés','Canto','Danza','Improvisación','Acento cordobés','Conducción','Equitación'],bio:'Actriz formada en Córdoba. Me interesa el trabajo frente a cámara y el desarrollo de personajes con profundidad y verdad.',presentation:'https://player.vimeo.com/video/76979871',reel:'https://player.vimeo.com/video/76979871',monologue:'https://player.vimeo.com/video/76979871'},
 {id:'tomas-peralta',name:'Tomás Peralta',gender:'actor',birth:'2002-11-19',city:'Córdoba Capital',available:true,student:true,featured:true,updated:'2026-08-12',photo:'https://randomuser.me/api/portraits/men/32.jpg',photos:['https://randomuser.me/api/portraits/men/32.jpg'],skills:['Improvisación','Inglés','Fútbol','Conducción'],bio:'Actor cordobés con experiencia en cortometrajes y publicidad.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'lucia-delgado',name:'Lucía Delgado',gender:'actriz',birth:'1999-02-02',city:'Córdoba Capital',available:true,student:false,featured:true,updated:'2026-07-29',photo:'https://randomuser.me/api/portraits/women/22.jpg',photos:['https://randomuser.me/api/portraits/women/22.jpg'],skills:['Canto','Teatro musical','Inglés'],bio:'Actriz y cantante orientada a proyectos audiovisuales.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'santiago-olivera',name:'Santiago Olivera',gender:'actor',birth:'1998-08-30',city:'Córdoba Capital',available:true,student:true,featured:true,updated:'2026-08-18',photo:'https://randomuser.me/api/portraits/men/54.jpg',photos:['https://randomuser.me/api/portraits/men/54.jpg'],skills:['Boxeo','Conducción','Inglés','Improvisación'],bio:'Actor para cine, publicidad y series.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'malena-figueroa',name:'Malena Figueroa',gender:'actriz',birth:'2003-05-21',city:'Villa Allende',available:true,student:true,featured:true,updated:'2026-08-01',photo:'https://randomuser.me/api/portraits/women/58.jpg',photos:['https://randomuser.me/api/portraits/women/58.jpg'],skills:['Danza','Inglés','Natación'],bio:'Actriz con formación en danza y entrenamiento frente a cámara.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'diego-alarcon',name:'Diego Alarcón',gender:'actor',birth:'1989-10-08',city:'Córdoba Capital',available:true,student:false,featured:true,updated:'2026-07-20',photo:'https://randomuser.me/api/portraits/men/48.jpg',photos:['https://randomuser.me/api/portraits/men/48.jpg'],skills:['Teatro','Conducción','Portugués'],bio:'Actor con experiencia en teatro independiente y producciones audiovisuales.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'carla-navarrete',name:'Carla Navarrete',gender:'actriz',birth:'2004-01-17',city:'Córdoba Capital',available:false,student:true,featured:false,updated:'2026-06-11',photo:'https://randomuser.me/api/portraits/women/12.jpg',photos:['https://randomuser.me/api/portraits/women/12.jpg'],skills:['Canto','Inglés','Improvisación'],bio:'Actriz joven con formación teatral.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'martin-ledesma',name:'Martín Ledesma',gender:'actor',birth:'1997-07-09',city:'Carlos Paz',available:true,student:true,featured:false,updated:'2026-08-04',photo:'https://randomuser.me/api/portraits/men/22.jpg',photos:['https://randomuser.me/api/portraits/men/22.jpg'],skills:['Deporte','Acento cordobés','Conducción'],bio:'Actor de Córdoba con disponibilidad para viajar.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'agustina-romano',name:'Agustina Romano',gender:'actriz',birth:'2000-12-01',city:'Córdoba Capital',available:true,student:false,featured:false,updated:'2026-08-10',photo:'https://randomuser.me/api/portraits/women/36.jpg',photos:['https://randomuser.me/api/portraits/women/36.jpg'],skills:['Actuación física','Danza','Canto'],bio:'Actriz orientada a cine y publicidad.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'lucas-ibanez',name:'Lucas Ibáñez',gender:'actor',birth:'1992-03-22',city:'Córdoba Capital',available:true,student:false,featured:false,updated:'2026-07-31',photo:'https://randomuser.me/api/portraits/men/75.jpg',photos:['https://randomuser.me/api/portraits/men/75.jpg'],skills:['Conducción','Deporte','Inglés'],bio:'Actor audiovisual con experiencia en publicidad.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'paula-santoro',name:'Paula Santoro',gender:'actriz',birth:'1995-06-14',city:'Río Ceballos',available:true,student:true,featured:false,updated:'2026-08-09',photo:'https://randomuser.me/api/portraits/women/50.jpg',photos:['https://randomuser.me/api/portraits/women/50.jpg'],skills:['Inglés','Improvisación','Yoga'],bio:'Actriz y docente con interés en proyectos independientes.',presentation:'https://player.vimeo.com/video/76979871'},
 {id:'valentino-ruiz',name:'Valentino Ruiz',gender:'actor',birth:'2005-09-02',city:'Córdoba Capital',available:true,student:true,featured:false,updated:'2026-08-16',photo:'https://randomuser.me/api/portraits/men/18.jpg',photos:['https://randomuser.me/api/portraits/men/18.jpg'],skills:['Danza','Acrobacia','Canto'],bio:'Actor joven con formación en movimiento y cámara.',presentation:'https://player.vimeo.com/video/76979871'}
];
