-- ===== V0.5 =====
-- Privilegios explícitos porque el proyecto fue creado con "Automatically expose new tables" desactivado.
grant select, update on public.profiles to authenticated;
grant select, update on public.notifications to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

-- Reportes públicos discretos. No exponen datos privados del actor.
create table if not exists public.profile_reports (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  reporter_user_id uuid references auth.users(id) on delete set null,
  reason text not null check (char_length(reason) between 5 and 500),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
alter table public.profile_reports enable row level security;
grant select, update on public.profile_reports to authenticated;
grant usage, select on sequence public.profile_reports_id_seq to authenticated;
drop policy if exists "admins read reports" on public.profile_reports;
create policy "admins read reports" on public.profile_reports for select to authenticated using (public.is_admin());
drop policy if exists "admins update reports" on public.profile_reports;
create policy "admins update reports" on public.profile_reports for update to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.submit_profile_report(actor_ref text, report_reason text)
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid;
begin
  if char_length(trim(coalesce(report_reason,''))) < 5 then raise exception 'El motivo es demasiado corto'; end if;
  select id into target_id from public.profiles
  where status='approved' and is_hidden=false and (slug=actor_ref or id::text=actor_ref) limit 1;
  if target_id is null then raise exception 'Perfil no encontrado'; end if;
  insert into public.profile_reports(actor_id,reporter_user_id,reason)
  values(target_id,auth.uid(),left(trim(report_reason),500));
end $$;
grant execute on function public.submit_profile_report(text,text) to anon, authenticated;

-- El admin puede eliminar una cuenta completa desde el panel.
create or replace function public.admin_delete_actor(target_id uuid)
returns void language plpgsql security definer set search_path=public,auth,storage as $$
begin
  if not public.is_admin() then raise exception 'Acceso restringido'; end if;
  if exists(select 1 from public.profiles where id=target_id and role='admin') then raise exception 'No se puede eliminar una cuenta administradora desde este panel'; end if;
  delete from storage.objects where bucket_id='actor-photos' and (storage.foldername(name))[1]=target_id::text;
  delete from auth.users where id=target_id;
end $$;
grant execute on function public.admin_delete_actor(uuid) to authenticated;
