-- RED DE ACTORES — V0.3
-- Ejecutar completo en Supabase > SQL Editor en un proyecto NUEVO para esta plataforma.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'actor' check (role in ('actor','admin')),
  status text not null default 'draft' check (status in ('draft','pending','approved','rejected')),
  display_name text,
  slug text unique,
  birth_date date,
  city text,
  bio text default '',
  skills text[] not null default '{}',
  is_available boolean not null default false,
  accepts_student_work boolean not null default false,
  photo_url text,
  photo_url_2 text,
  photo_url_3 text,
  presentation_url text,
  reel_url text,
  monologue_url text,
  is_featured boolean not null default false,
  is_verified boolean not null default false,
  is_hidden boolean not null default false,
  rejection_reason text,
  submitted_at timestamptz,
  approved_at timestamptz,
  last_profile_confirmation timestamptz default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint max_seven_skills check (cardinality(skills) <= 7)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id) values(new.id) on conflict do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

alter table public.profiles enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "owner reads profile" on public.profiles;
create policy "owner reads profile" on public.profiles for select using (auth.uid()=id or public.is_admin());
drop policy if exists "owner updates profile" on public.profiles;
create policy "owner updates profile" on public.profiles for update using (auth.uid()=id or public.is_admin()) with check (auth.uid()=id or public.is_admin());

drop policy if exists "user reads notifications" on public.notifications;
create policy "user reads notifications" on public.notifications for select using (auth.uid()=user_id or public.is_admin());
drop policy if exists "user updates notifications" on public.notifications;
create policy "user updates notifications" on public.notifications for update using (auth.uid()=user_id or public.is_admin());

-- Los perfiles públicos salen SOLO por estas RPC: jamás devuelven birth_date.
create or replace function public.get_public_actors()
returns table(
  id uuid, slug text, display_name text, age_years int, city text, bio text, skills text[],
  is_available boolean, accepts_student_work boolean, photo_url text, photo_url_2 text, photo_url_3 text,
  presentation_url text, reel_url text, monologue_url text, is_featured boolean, is_verified boolean, updated_at timestamptz
)
language sql stable security definer set search_path=public as $$
  select p.id,p.slug,p.display_name,
    date_part('year',age(current_date,p.birth_date))::int,
    p.city,p.bio,p.skills,(p.is_available and coalesce(p.last_profile_confirmation,p.created_at) >= now()-interval '1 year') as is_available,p.accepts_student_work,p.photo_url,p.photo_url_2,p.photo_url_3,
    p.presentation_url,p.reel_url,p.monologue_url,p.is_featured,p.is_verified,p.updated_at
  from public.profiles p
  where p.status='approved' and p.is_hidden=false and p.display_name is not null
  order by p.is_featured desc,p.updated_at desc;
$$;

grant execute on function public.get_public_actors() to anon, authenticated;

create or replace function public.get_public_actor(actor_ref text)
returns table(
  id uuid, slug text, display_name text, age_years int, city text, bio text, skills text[],
  is_available boolean, accepts_student_work boolean, photo_url text, photo_url_2 text, photo_url_3 text,
  presentation_url text, reel_url text, monologue_url text, is_featured boolean, is_verified boolean, updated_at timestamptz
)
language sql stable security definer set search_path=public as $$
  select p.id,p.slug,p.display_name,
    date_part('year',age(current_date,p.birth_date))::int,
    p.city,p.bio,p.skills,(p.is_available and coalesce(p.last_profile_confirmation,p.created_at) >= now()-interval '1 year') as is_available,p.accepts_student_work,p.photo_url,p.photo_url_2,p.photo_url_3,
    p.presentation_url,p.reel_url,p.monologue_url,p.is_featured,p.is_verified,p.updated_at
  from public.profiles p
  where p.status='approved' and p.is_hidden=false and (p.slug=actor_ref or p.id::text=actor_ref)
  limit 1;
$$;

grant execute on function public.get_public_actor(text) to anon, authenticated;

-- Notificaciones automáticas al aprobar/rechazar.
create or replace function public.notify_moderation()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if old.status is distinct from new.status and new.status='approved' then
    insert into public.notifications(user_id,type,title,body) values(new.id,'profile_approved','Perfil aprobado','Tu perfil ya está visible en Red de Actores.');
  elsif old.status is distinct from new.status and new.status='rejected' then
    insert into public.notifications(user_id,type,title,body) values(new.id,'profile_rejected','Tu perfil necesita correcciones',coalesce(new.rejection_reason,'Revisá tu perfil.'));
  end if;
  return new;
end $$;

drop trigger if exists profiles_moderation_notification on public.profiles;
create trigger profiles_moderation_notification after update on public.profiles for each row execute procedure public.notify_moderation();

-- Storage: bucket público porque las fotos aprobadas forman parte del perfil público.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('actor-photos','actor-photos',true,3145728,array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public=true,file_size_limit=3145728,allowed_mime_types=array['image/jpeg','image/png','image/webp'];

drop policy if exists "actors upload own photos" on storage.objects;
create policy "actors upload own photos" on storage.objects for insert to authenticated
with check (bucket_id='actor-photos' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "actors update own photos" on storage.objects;
create policy "actors update own photos" on storage.objects for update to authenticated
using (bucket_id='actor-photos' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "actors delete own photos" on storage.objects;
create policy "actors delete own photos" on storage.objects for delete to authenticated
using (bucket_id='actor-photos' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_admin()));

-- Renovación anual: la plataforma considera NO DISPONIBLE a quien lleva más de 1 año sin confirmar.
-- Esta función puede ejecutarse con un cron diario más adelante.
create or replace function public.expire_old_availability()
returns void language sql security definer set search_path=public as $$
  update public.profiles set is_available=false
  where is_available=true and coalesce(last_profile_confirmation,created_at) < now()-interval '1 year';
$$;

-- IMPORTANTE: después de crear tu usuario administrador, ejecutá UNA VEZ reemplazando el email:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='TU_EMAIL_ADMIN');

-- Blindaje: un actor NO puede auto-aprobarse, hacerse admin, destacarse, verificarse ni ocultarse.
create or replace function public.protect_moderation_fields()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if public.is_admin() then return new; end if;
  if auth.uid()=old.id then
    new.role := old.role;
    new.is_featured := old.is_featured;
    new.is_verified := old.is_verified;
    new.is_hidden := old.is_hidden;
    new.approved_at := old.approved_at;
    new.rejection_reason := old.rejection_reason;

    -- Primera presentación o reenvío tras rechazo: puede pasar a pending.
    -- Una vez aprobado, los cambios cotidianos quedan publicados sin nueva revisión.
    if old.status in ('draft','rejected') and new.status='pending' then
      null;
    else
      new.status := old.status;
    end if;
  end if;
  return new;
end $$;

drop trigger if exists protect_profiles_moderation on public.profiles;
create trigger protect_profiles_moderation before update on public.profiles
for each row execute procedure public.protect_moderation_fields();

create or replace function public.set_profile_slug()
returns trigger language plpgsql set search_path=public as $$
begin
  if new.display_name is not null and (new.slug is null or new.slug='') then
    new.slug := trim(both '-' from regexp_replace(lower(translate(new.display_name,'áéíóúüñÁÉÍÓÚÜÑ','aeiouunAEIOUUN')),'[^a-z0-9]+','-','g')) || '-' || left(new.id::text,6);
  end if;
  return new;
end $$;

drop trigger if exists profiles_set_slug on public.profiles;
create trigger profiles_set_slug before insert or update of display_name on public.profiles
for each row execute procedure public.set_profile_slug();

-- ===== V0.5 =====
-- Privilegios explícitos porque el proyecto fue creado con "Automatically expose new tables" desactivado.
grant select, update on public.profiles to authenticated;
grant select, update on public.notifications to authenticated;
grant usage, select on sequence public.notifications_id_seq to authenticated;

-- Reportes públicos discretos. No exponen datos privados del actor.
create table if not exists public.profile_reports (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  reporter_user_id uuid references auth.users(id) on delete set null,
  reason text not null check (char_length(reason) between 5 and 500),
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
alter table public.profile_reports enable row level security;
grant select, update on public.profile_reports to authenticated;
grant usage, select on sequence public.profile_reports_id_seq to authenticated;
drop policy if exists "admins read reports" on public.profile_reports;
create policy "admins read reports" on public.profile_reports for select to authenticated using (public.is_admin());
drop policy if exists "admins update reports" on public.profile_reports;
create policy "admins update reports" on public.profile_reports for update to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace function public.submit_profile_report(actor_ref text, report_reason text)
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid;
begin
  if char_length(trim(coalesce(report_reason,''))) < 5 then raise exception 'El motivo es demasiado corto'; end if;
  select id into target_id from public.profiles
  where status='approved' and is_hidden=false and (slug=actor_ref or id::text=actor_ref) limit 1;
  if target_id is null then raise exception 'Perfil no encontrado'; end if;
  insert into public.profile_reports(actor_id,reporter_user_id,reason)
  values(target_id,auth.uid(),left(trim(report_reason),500));
end $$;
grant execute on function public.submit_profile_report(text,text) to anon, authenticated;

-- El admin puede eliminar una cuenta completa desde el panel.
create or replace function public.admin_delete_actor(target_id uuid)
returns void language plpgsql security definer set search_path=public,auth,storage as $$
begin
  if not public.is_admin() then raise exception 'Acceso restringido'; end if;
  if exists(select 1 from public.profiles where id=target_id and role='admin') then raise exception 'No se puede eliminar una cuenta administradora desde este panel'; end if;
  delete from storage.objects where bucket_id='actor-photos' and (storage.foldername(name))[1]=target_id::text;
  delete from auth.users where id=target_id;
end $$;
grant execute on function public.admin_delete_actor(uuid) to authenticated;
