-- RED DE ACTORES — V0.6
-- Ejecutar UNA VEZ después de supabase-v0.5-migration.sql

-- 1) Nuevo estado administrativo: cambios solicitados.
alter table public.profiles drop constraint if exists profiles_status_check;
alter table public.profiles add constraint profiles_status_check
  check (status in ('draft','pending','approved','rejected','changes_requested'));

create or replace function public.notify_moderation()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if old.status is distinct from new.status and new.status='approved' then
    insert into public.notifications(user_id,type,title,body)
    values(new.id,'profile_approved','Perfil aprobado','Tu perfil ya está visible en Red de Actores.');
  elsif old.status is distinct from new.status and new.status='rejected' then
    insert into public.notifications(user_id,type,title,body)
    values(new.id,'profile_rejected','Tu perfil necesita correcciones',coalesce(new.rejection_reason,'Revisá tu perfil.'));
  elsif old.status is distinct from new.status and new.status='changes_requested' then
    insert into public.notifications(user_id,type,title,body)
    values(new.id,'changes_requested','Córdoba Casting solicitó cambios',coalesce(new.rejection_reason,'Revisá tu perfil y corregí lo indicado.'));
  end if;
  return new;
end $$;

create or replace function public.protect_moderation_fields()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if public.is_admin() then return new; end if;
  if auth.uid()=old.id then
    new.role := old.role;
    new.is_featured := old.is_featured;
    new.is_verified := old.is_verified;
    new.is_hidden := old.is_hidden;
    new.approved_at := old.approved_at;
    new.rejection_reason := old.rejection_reason;

    if old.status in ('draft','rejected','changes_requested') and new.status='pending' then
      null;
    else
      new.status := old.status;
    end if;
  end if;
  return new;
end $$;

-- 2) Contacto privado desde el perfil público.
create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  sender_name text not null check (char_length(sender_name) between 2 and 100),
  sender_email text not null check (char_length(sender_email) between 5 and 200),
  message text not null check (char_length(message) between 10 and 1200),
  created_at timestamptz not null default now(),
  read_at timestamptz
);
alter table public.contact_requests enable row level security;
grant select, update on public.contact_requests to authenticated;
grant usage, select on sequence public.contact_requests_id_seq to authenticated;

drop policy if exists "actor reads contact requests" on public.contact_requests;
create policy "actor reads contact requests" on public.contact_requests for select to authenticated
using (actor_id=auth.uid() or public.is_admin());
drop policy if exists "actor marks contact requests" on public.contact_requests;
create policy "actor marks contact requests" on public.contact_requests for update to authenticated
using (actor_id=auth.uid() or public.is_admin()) with check (actor_id=auth.uid() or public.is_admin());

create or replace function public.submit_contact_request(actor_ref text, sender_name text, sender_email text, contact_message text)
returns void language plpgsql security definer set search_path=public as $$
declare target_id uuid;
begin
  select id into target_id from public.profiles
  where status='approved' and is_hidden=false and (slug=actor_ref or id::text=actor_ref) limit 1;
  if target_id is null then raise exception 'Perfil no encontrado'; end if;
  insert into public.contact_requests(actor_id,sender_name,sender_email,message)
  values(target_id,left(trim(sender_name),100),left(trim(sender_email),200),left(trim(contact_message),1200));
  insert into public.notifications(user_id,type,title,body)
  values(target_id,'contact_request','Nuevo contacto profesional','Una persona quiere contactarte desde tu perfil de Red de Actores.');
end $$;
grant execute on function public.submit_contact_request(text,text,text,text) to anon, authenticated;

-- 3) Castings y postulaciones.
create table if not exists public.castings (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  project_name text,
  category text,
  city text default 'Córdoba',
  description text not null,
  profile_sought text,
  is_paid boolean not null default true,
  deadline date,
  is_open boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.castings enable row level security;
grant select on public.castings to anon, authenticated;
grant insert, update, delete on public.castings to authenticated;

drop policy if exists "public reads open castings" on public.castings;
create policy "public reads open castings" on public.castings for select using (is_open=true or public.is_admin());
drop policy if exists "admin manages castings" on public.castings;
create policy "admin manages castings" on public.castings for all to authenticated using (public.is_admin()) with check (public.is_admin());

create table if not exists public.casting_applications (
  id bigint generated by default as identity primary key,
  casting_id uuid not null references public.castings(id) on delete cascade,
  actor_id uuid not null references public.profiles(id) on delete cascade,
  message text,
  created_at timestamptz not null default now(),
  unique(casting_id,actor_id)
);
alter table public.casting_applications enable row level security;
grant select, insert, delete on public.casting_applications to authenticated;
grant usage, select on sequence public.casting_applications_id_seq to authenticated;

drop policy if exists "actor reads own applications" on public.casting_applications;
create policy "actor reads own applications" on public.casting_applications for select to authenticated
using (actor_id=auth.uid() or public.is_admin());
drop policy if exists "actor applies with own profile" on public.casting_applications;
create policy "actor applies with own profile" on public.casting_applications for insert to authenticated
with check (actor_id=auth.uid() and exists(select 1 from public.profiles p where p.id=auth.uid() and p.status='approved'));
drop policy if exists "actor removes own application" on public.casting_applications;
create policy "actor removes own application" on public.casting_applications for delete to authenticated
using (actor_id=auth.uid() or public.is_admin());
